In [1]:
from __future__ import print_function
import argparse
import random
import numpy as np
import chainer
from chainer import training
from chainer.training import extensions

In [16]:
import chainer
import chainer.functions as F
import chainer.links as L
import numpy as np

x = np.array([range(5)])
for i in xrange(1,5):
    x = np.vstack((x,range(i,5+i)))
print x

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [22]:
x0 = np.array([range(5)])
x1 = np.array([range(1,6)])
x2 = np.array([range(2,7)])
x3 = np.array([range(3,8)])
x4 = np.array([range(4,9)])
s = F.concat((x0,x1,x2,x3,x4),axis=1)
print s.data

[[0 1 2 3 4 1 2 3 4 5 2 3 4 5 6 3 4 5 6 7 4 5 6 7 8]]


In [24]:
x0 = L.Linear(5,50)
x = np.array([range(5)],dtype=np.float32)
y = x0(x)
y.data

array([[-3.23035049, -0.89959276,  0.35255027, -0.29854244, -2.99487305,
        -2.19102573,  0.4363513 , -3.21709347,  0.18594825,  1.6221447 ,
        -1.66413987, -1.68397307,  0.6071099 , -0.99840033,  0.70045364,
         0.80429351, -0.73693973,  1.49958062, -2.7808814 , -1.96280718,
        -1.57712483, -0.11296523,  0.50114906, -2.71134257,  0.08066076,
         1.72019386, -2.53416443,  2.10865974, -4.07359695,  0.53148246,
        -5.25796223,  1.5724864 ,  0.68154639, -0.21349406,  2.89456367,
         5.58018112, -3.34453487,  0.54504085,  1.9793098 , -1.06478357,
        -3.25890255,  2.22458506,  1.22888863, -3.30351114, -0.77873874,
         2.34976125, -2.19915152,  3.14596391,  1.84963989,  0.16356397]], dtype=float32)

In [25]:
x0 = L.Linear(5,50)
x1 = L.Linear(5,50)
x2 = L.Linear(5,50)
x3 = L.Linear(5,50)
x4 = L.Linear(5,50)
X0 =  np.array([range(5)],dtype=np.float32)
X1 =  np.array([range(1,6)],dtype=np.float32)
X2 =  np.array([range(2,7)],dtype=np.float32)
X3 =  np.array([range(3,8)],dtype=np.float32)
X4 =  np.array([range(4,9)],dtype=np.float32)

In [30]:
print X0
print x0(X0).data
print F.relu(x0(X0)).data


#F.concat((x0,x1,x2,x3,x4),axis=1)

[[ 0.  1.  2.  3.  4.]]
[[-1.44477487  1.66910672 -0.47500563 -1.81804705 -4.15353251 -0.05189142
  -2.35386848  0.8230353  -1.25348616 -0.72115445 -2.02946401  1.18666744
  -1.01529002 -0.73725301 -0.12805259  1.78450465  1.14421463  1.67224574
   0.96545821  1.00655222  0.12165543 -1.35251105 -0.45995671 -5.08067465
   0.76519865  1.17973244 -3.98685718  2.2305212  -0.21071315 -0.32650495
  -1.71446204  1.04412091 -1.43571162  3.2735939  -1.61206949  2.02214432
   0.44891042 -1.0503664   0.95042598  2.23634768  3.32941389 -3.38624001
   0.34196928 -3.77349591  2.46931291 -3.45697498 -0.25009108 -0.14086163
  -1.60457945 -0.22005904]]
[[ 0.          1.66910672  0.          0.          0.          0.          0.
   0.8230353   0.          0.          0.          1.18666744  0.          0.
   0.          1.78450465  1.14421463  1.67224574  0.96545821  1.00655222
   0.12165543  0.          0.          0.          0.76519865  1.17973244
   0.          2.2305212   0.          0.          0

In [35]:
y = F.concat((x0(X0),x1(X1),x2(X2),x3(X3),x4(X4)),axis=1)
y.data

array([[ -1.44477487,   1.66910672,  -0.47500563,  -1.81804705,
         -4.15353251,  -0.05189142,  -2.35386848,   0.8230353 ,
         -1.25348616,  -0.72115445,  -2.02946401,   1.18666744,
         -1.01529002,  -0.73725301,  -0.12805259,   1.78450465,
          1.14421463,   1.67224574,   0.96545821,   1.00655222,
          0.12165543,  -1.35251105,  -0.45995671,  -5.08067465,
          0.76519865,   1.17973244,  -3.98685718,   2.2305212 ,
         -0.21071315,  -0.32650495,  -1.71446204,   1.04412091,
         -1.43571162,   3.2735939 ,  -1.61206949,   2.02214432,
          0.44891042,  -1.0503664 ,   0.95042598,   2.23634768,
          3.32941389,  -3.38624001,   0.34196928,  -3.77349591,
          2.46931291,  -3.45697498,  -0.25009108,  -0.14086163,
         -1.60457945,  -0.22005904,   2.37580228,  -3.55933762,
         -0.91901922,   3.68664646,  -4.54829025,  -7.91051579,
          4.13310289,  -2.43942404,  -0.72390246,   6.21593761,
          4.87554741,   7.03650284,  -1.

In [36]:
l1 = L.Linear(250,250)
s = l1(y)

In [37]:
s.data

array([[ -5.73396301,  -4.71343946,   0.9495855 ,  -0.93359506,
          3.71211028,   0.07293823,  -7.07951736,   3.05272508,
          0.62499106,  -0.84293687,   7.82073689,   5.49160528,
         -0.35018599,  -4.79523563,   0.27637213,  -0.47997147,
         -5.95733881,  -7.56582594,   7.22937918,   3.23361778,
         -1.00072443, -13.27741623,   4.58362007,  -0.87390852,
          9.80530167,  -4.56243849,   1.37961543,   5.91709614,
         -6.36962414,  -0.60047352,   4.61717844,   1.64443612,
         -3.06508875, -10.45810127,   0.0881223 ,   2.19514227,
         -3.07270193,   0.83005023,   5.92919159,  -4.90198946,
          0.28255662,   5.76656914,   0.91110039,  -0.97530568,
          2.16356301,   0.95778704,  -1.19613218,   2.59705091,
         -4.08356714,   1.22752166,  -6.79842663,  -3.93853712,
          1.83004177,  -1.82399821,   1.37630415,   1.77537715,
          2.89468622,  -0.54376602,   2.86266136,   1.72400308,
         -2.18467903, -10.73721886,   6.

In [38]:
ss = F.relu(s)
ss.data

array([[  0.        ,   0.        ,   0.9495855 ,   0.        ,
          3.71211028,   0.07293823,   0.        ,   3.05272508,
          0.62499106,   0.        ,   7.82073689,   5.49160528,
          0.        ,   0.        ,   0.27637213,   0.        ,
          0.        ,   0.        ,   7.22937918,   3.23361778,
          0.        ,   0.        ,   4.58362007,   0.        ,
          9.80530167,   0.        ,   1.37961543,   5.91709614,
          0.        ,   0.        ,   4.61717844,   1.64443612,
          0.        ,   0.        ,   0.0881223 ,   2.19514227,
          0.        ,   0.83005023,   5.92919159,   0.        ,
          0.28255662,   5.76656914,   0.91110039,   0.        ,
          2.16356301,   0.95778704,   0.        ,   2.59705091,
          0.        ,   1.22752166,   0.        ,   0.        ,
          1.83004177,   0.        ,   1.37630415,   1.77537715,
          2.89468622,   0.        ,   2.86266136,   1.72400308,
          0.        ,   0.        ,   6.

In [ ]:
class ChaosNN(Chain):
    def __init__(self):
        super(ChaosNN,self).__init__(
        x0 = L.Linear(5,50)
        x1 = L.Linear(5,50)
        x2 = L.Linear(5,50)
        x3 = L.Linear(5,50)
        x4 = L.Linear(5,50)
            
        l1 = L.Linear(250,250)
        l2 = L.Linear(250,250)
        l3 = L.Linear(250,250)
        l4 = L.Linear(250,250)
        l5 = L.Linear(250,250)
        l6 = L.Linear(250,250)
        l7 = L.Linear(250,250)
        l8 = L.Linear(250,250)
        l9 = L.Linear(250,250)
        l10 = L.Linear(250,250)
            
        output = L.Linear(250,5)
        )
    def __call__(self,x):
        h1 = F.relu(self.x0(x))
        h2 = F.relu(self.x1(x))
        h3 = F.relu(self.x2(x))
        h4 = F.relu(self.x3(x))
        h5 = F.relu(self.x4(x))
        h = F.relu(F.concat(h1,h2,h3,h4,h5),axis=1)
        h = F.relu(self.l1(x))
        h = F.relu(self.l2(x))
        h = F.relu(self.l3(x))
        h = F.relu(self.l4(x))
        h = F.relu(self.l5(x))
        h = F.relu(self.l6(x))
        h = F.relu(self.l7(x))
        h = F.relu(self.l8(x))
        h = F.relu(self.l9(x))
        h = F.relu(self.l10(x))
        loss = F.mean_squared_error(h,y)
        return loss


        

In [ ]:
def main():
    parser = argparse.ArgumentParser(description='ChaosNN')
    parser.add_argument('--batchsize', '-b', type=int, default=100,help='Number of images in each mini-batch')
    parser.add_argument('--epoch', '-e', type=int, default=20,help='Number of sweeps over the dataset to train')
    parser.add_argument('--frequency', '-f', type=int, default=-1,help='Frequency of taking a snapshot')
    parser.add_argument('--gpu', '-g', type=int, default=-1,help='GPU ID (negative value indicates CPU)')
    parser.add_argument('--out', '-o', default='result',help='Directory to output the result')
    parser.add_argument('--resume', '-r', default='',help='Resume the training from snapshot')
    parser.add_argument('--unit', '-u', type=int, default=1000,help='Number of units')
    args = parser.parse_args()
    print('GPU: {}'.format(args.gpu))
    print('# unit: {}'.format(args.unit))
    print('# Minibatch-size: {}'.format(args.batchsize))
    print('# epoch: {}'.format(args.epoch))
    print('')
# Set up a neural network to train
# Classifier reports softmax cross entropy loss and accuracy at every
# iteration, which will be used by the PrintReport extension below.
    model = ChaosNN()
    if args.gpu >= 0:
        chainer.cuda.get_device(args.gpu).use() # Make a specified GPU current
        model.to_gpu() # Copy the model to the GPU
# Setup an optimizer
    optimizer = chainer.optimizers.Adam()
    optimizer.setup(model)
# Load the MNIST dataset
    train, test = chainer.datasets.get_mnist()
    train_iter = chainer.iterators.SerialIterator(train, args.batchsize)
    test_iter = chainer.iterators.SerialIterator(test, args.batchsize,repeat=False, shuffle=False)
# Set up a trainer
    updater = training.StandardUpdater(train_iter, optimizer, device=args.gpu)
    trainer = training.Trainer(updater, (args.epoch, 'epoch'), out=args.out)
# Evaluate the model with the test dataset for each epoch
    trainer.extend(extensions.Evaluator(test_iter, model, device=args.gpu))
# Dump a computational graph from 'loss' variable at the first iteration
# The "main" refers to the target link of the "main" optimizer.
    trainer.extend(extensions.dump_graph('main/loss'))
# Take a snapshot for each specified epoch
    frequency = args.epoch if args.frequency == -1 else max(1, args.frequency)
    trainer.extend(extensions.snapshot(), trigger=(frequency, 'epoch'))
# Write a log of evaluation statistics for each epoch
    trainer.extend(extensions.LogReport())
# Save two plot images to the result dir
    if extensions.PlotReport.available():
        trainer.extend(extensions.PlotReport(['main/loss', 'validation/main/loss'],'epoch', file_name='loss.png'))
        trainer.extend(extensions.PlotReport(['main/accuracy', 'validation/main/accuracy'],'epoch', file_name='accuracy.png'))
# Print selected entries of the log to stdout
# Here "main" refers to the target link of the "main" optimizer again, and
# "validation" refers to the default name of the Evaluator extension.
# Entries other than 'epoch' are reported by the Classifier link, called by
# either the updater or the evaluator.
    trainer.extend(extensions.PrintReport(['epoch', 'main/loss', 'validation/main/loss','main/accuracy', 'validation/main/accuracy', 'elapsed_time']))
# Print a progress bar to stdout
    trainer.extend(extensions.ProgressBar())
    if args.resume:
# Resume from a snapshot
        chainer.serializers.load_npz(args.resume, trainer)
# Run the training
    trainer.run()
if __name__ == '__main__':
main()