In [1]:
import pandas as pd
import pandas_datareader.data as wb
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from datetime import datetime
start = datetime(1970,1,1)
end = datetime(2016,7,20)

df = wb.DataReader("^N225","yahoo",start,end)


/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning


In [3]:
data = df["Adj Close"]
print len(data)
data = list(data)

8015


In [4]:
def split_data(data):
    
    train,val,test=data[:5125],data[5125:(5125+1285)],data[(5125+1285):]
    
    return train,val,test

train,val,test=split_data(data)
print len(train),len(val),len(test)
print train

5125 1285 1605
[9927.0, 9947.0, 9961.0, 9954.0, 10016.0, 10073.0, 10104.0, 10151.0, 10156.0, 10100.0, 10098.0, 10104.0, 10071.0, 10023.0, 10115.0, 10180.0, 10181.0, 10236.0, 10196.0, 10201.0, 10156.0, 10134.0, 10121.0, 10061.0, 10100.0, 10002.0, 9959.0, 9963.0, 9830.0, 9892.0, 9897.0, 9925.0, 9938.0, 9971.0, 9948.0, 9940.0, 9963.0, 10071.0, 10074.0, 10031.0, 9920.0, 9948.0, 10089.0, 10059.0, 10021.0, 9959.0, 9997.0, 10087.0, 10195.0, 10324.0, 10347.0, 10458.0, 10479.0, 10414.0, 10456.0, 10506.0, 10484.0, 10528.0, 10701.0, 10802.0, 10929.0, 11050.0, 10934.0, 11002.0, 10993.0, 10915.0, 10890.0, 10915.0, 10939.0, 10987.0, 11015.0, 11020.0, 10906.0, 10933.0, 10783.0, 10803.0, 10801.0, 10762.0, 10866.0, 10902.0, 10981.0, 11013.0, 11105.0, 11130.0, 11159.0, 11052.0, 11060.0, 10880.0, 10833.0, 10563.0, 10605.0, 10620.0, 10341.0, 10126.0, 10165.0, 10062.0, 10023.0, 10251.0, 10142.0, 10116.0, 10164.0, 10141.0, 9940.0, 9913.0, 10132.0, 10258.0, 10254.0, 10316.0, 10350.0, 10377.0, 10325.0, 10276.

In [5]:
def group_data(data):
    data_ = []
    for t in xrange(len(data)-25):
        data_.append(data[t:t+25:5])
    return data_
train = group_data(train)
val = group_data(val)
test = group_data(test)
print len(train),len(val),len(test)

5100 1260 1580


In [6]:
def split_xy(data):
    data_x=[]
    data_y=[]
    for i in xrange(len(data)-25):
        k = data[i:i+25:5]
        data_x.append(k)
        j = data[5+i]
        data_y.append(j)
    data_x = np.array(data_x,dtype=np.float32)
    data_y = np.array(data_y,dtype=np.float32)
    return data_x,data_y
train_x ,train_y = split_xy(train)
val_x,val_y = split_xy(val)
test_x,test_y = split_xy(test)

In [7]:
print train_x[0]

[[  9927.  10073.  10098.  10180.  10156.]
 [ 10073.  10098.  10180.  10156.  10002.]
 [ 10098.  10180.  10156.  10002.   9897.]
 [ 10180.  10156.  10002.   9897.   9940.]
 [ 10156.  10002.   9897.   9940.   9920.]]


In [8]:
print train_x[0][0]

[  9927.  10073.  10098.  10180.  10156.]


In [9]:
print train_y[0]

[ 10073.  10098.  10180.  10156.  10002.]


In [10]:
for i in xrange(5):
    print train_x[i][0]
    print train_x[i][1]
    print train_x[i][2]
    print train_x[i][3]
    print train_x[i][4]
    print train_y[i:i+5]
    print "-"*10

[  9927.  10073.  10098.  10180.  10156.]
[ 10073.  10098.  10180.  10156.  10002.]
[ 10098.  10180.  10156.  10002.   9897.]
[ 10180.  10156.  10002.   9897.   9940.]
[ 10156.  10002.   9897.   9940.   9920.]
[[ 10073.  10098.  10180.  10156.  10002.]
 [ 10104.  10104.  10181.  10134.   9959.]
 [ 10151.  10071.  10236.  10121.   9963.]
 [ 10156.  10023.  10196.  10061.   9830.]
 [ 10100.  10115.  10201.  10100.   9892.]]
----------
[  9947.  10104.  10104.  10181.  10134.]
[ 10104.  10104.  10181.  10134.   9959.]
[ 10104.  10181.  10134.   9959.   9925.]
[ 10181.  10134.   9959.   9925.   9963.]
[ 10134.   9959.   9925.   9963.   9948.]
[[ 10104.  10104.  10181.  10134.   9959.]
 [ 10151.  10071.  10236.  10121.   9963.]
 [ 10156.  10023.  10196.  10061.   9830.]
 [ 10100.  10115.  10201.  10100.   9892.]
 [ 10098.  10180.  10156.  10002.   9897.]]
----------
[  9961.  10151.  10071.  10236.  10121.]
[ 10151.  10071.  10236.  10121.   9963.]
[ 10071.  10236.  10121.   9963.   9938.]


In [11]:
from chainer import cuda
cuda.get_device(0).use()
xp = cuda.cupy
train_x = xp.array(train_x)
print train_x.shape

(5075, 5, 5)


/usr/local/lib/python2.7/dist-packages/chainer/cuda.py:92: UserWarning: cuDNN is not enabled.
Please reinstall chainer after you install cudnn
(see https://github.com/pfnet/chainer#installation).
  'cuDNN is not enabled.\n'


In [12]:
print type(train_x)

<type 'cupy.core.core.ndarray'>


In [13]:
def organize_data(data):
    data_ = np.empty(5)
    for i in data:
        x = np.array(i)
        data_ = np.vstack((data_,x))
    data_ = data_[1:]
    return data_
train = organize_data(train)
val = organize_data(val)
test = organize_data(test)

In [14]:
def label_data(data,time_steps,labels=False):
    df = []
    for i in xrange(len(data)-time_steps):
        if labels:
            try:
                df.append(data[i+time_steps]).as_matrix()
            except AttributeError:
                df.append(data[i+time_steps])
        else:
            data_ = data[i:i+time_steps]
            df.append(data_ if len(data_.shape) > 1 else [[i] for i in data_])
    return np.array(df)
time_steps = 5
train_x = label_data(train_np,time_steps,labels=False)
train_y = label_data(train_np,time_steps,labels=True)

NameError: name 'train_np' is not defined

In [ ]:
data = np.vstack((data0_5,data1_5))

In [ ]:
print data

In [ ]:
data = np.vstack((data,data2_5))
data = np.vstack((data,data3_5))
data = np.vstack((data,data4_5))
print data

In [ ]:
print data.T